"""
R Code Generator
Converts SAS AST to optimized R code with dplyr/tidyr
"""

from typing import List, Dict, Any, Optional
from jinja2 import Template

class RCodeGenerator:
    """
    Generates R code from SAS Abstract Syntax Tree
    Handles all major SAS procedures and converts to tidyverse equivalents
    """
    
    def __init__(self):
        self.r_code_lines = []
        self.current_dataset = None
        self.variables = []
        self.data_step_active = False
        self.inline_data = []
    
    def generate(self, ast: List[Dict[str, Any]]) -> str:
        """Generate R code from AST"""
        self.r_code_lines = []
        self.add_header()
        
        for node in ast:
            self._process_node(node)
        
        return '\n'.join(self.r_code_lines)
    
    def add_header(self):
        """Add R library imports"""
        self.r_code_lines.extend([
            "# Auto-generated R code from SAS",
            "# Generated by SAS to R Automation Platform",
            "",
            "# Load required libraries",
            "library(dplyr)",
            "library(tidyr)",
            "library(haven)  # For reading SAS datasets",
            "",
        ])
    
    def _process_node(self, node: Dict[str, Any]):
        """Process individual AST node"""
        node_type = node.get('type')
        
        if node_type == 'data_step':
            self._generate_data_step(node)
        
        elif node_type == 'set':
            self._generate_set(node)
        
        elif node_type == 'input':
            self._generate_input(node)
        
        elif node_type == 'datalines':
            self.data_step_active = True
            self.r_code_lines.append("# Reading inline data")
        
        elif node_type == 'assignment':
            self._generate_assignment(node)
        
        elif node_type == 'if_statement':
            self._generate_if_statement(node)
        
        elif node_type == 'proc_means':
            self._generate_proc_means(node)
        
        elif node_type == 'proc_freq':
            self._generate_proc_freq(node)
        
        elif node_type == 'proc_sort':
            self._generate_proc_sort(node)
        
        elif node_type == 'proc_sql':
            self._generate_proc_sql(node)
        
        elif node_type == 'var':
            self.variables = node.get('variables', [])
        
        elif node_type == 'by':
            self.by_variables = node.get('variables', [])
            self.by_descending = node.get('descending', False)
        
        elif node_type == 'class':
            self.class_variables = node.get('variables', [])
        
        elif node_type == 'tables':
            self.table_variables = node.get('variables', [])
        
        elif node_type == 'run' or node_type == 'quit':
            if self.data_step_active:
                self._finalize_data_step()
            self.r_code_lines.append("")
    
    def _generate_data_step(self, node: Dict[str, Any]):
        """Generate DATA step"""
        dataset = node.get('dataset', 'data')
        self.current_dataset = dataset
        self.r_code_lines.append(f"# DATA step: Creating dataset '{dataset}'")
    
    def _generate_set(self, node: Dict[str, Any]):
        """Generate SET statement"""
        dataset = node.get('dataset', 'data')
        self.r_code_lines.append(f"{self.current_dataset} <- {dataset}")
    
    def _generate_input(self, node: Dict[str, Any]):
        """Generate INPUT statement with variable definitions"""
        variables = node.get('variables', [])
        self.variables = variables
        
        var_names = [v['name'] for v in variables]
        self.r_code_lines.append(f"# Variables: {', '.join(var_names)}")
    
    def _finalize_data_step(self):
        """Finalize DATA step with inline data"""
        if not self.variables or not self.inline_data:
            return
        
        # Create data.frame from inline data
        var_names = [v['name'] for v in self.variables]
        
        self.r_code_lines.append(f"{self.current_dataset} <- data.frame(")
        
        for i, var in enumerate(self.variables):
            var_name = var['name']
            var_type = var['type']
            
            # Extract column data
            col_data = []
            for row in self.inline_data:
                if i < len(row):
                    val = row[i]
                    if val == '.' or val == '':
                        col_data.append('NA')
                    elif var_type == 'character':
                        col_data.append(f"'{val}'")
                    else:
                        col_data.append(val)
                else:
                    col_data.append('NA')
            
            col_str = f"  {var_name} = c({', '.join(col_data)})"
            if i < len(self.variables) - 1:
                col_str += ","
            self.r_code_lines.append(col_str)
        
        self.r_code_lines.append("  stringsAsFactors = FALSE")
        self.r_code_lines.append(")")
        
        self.data_step_active = False
        self.inline_data = []
    
    def _generate_assignment(self, node: Dict[str, Any]):
        """Generate variable assignment"""
        variable = node.get('variable')
        expression = node.get('expression')
        
        # Convert SAS expression to R
        r_expression = self._convert_expression(expression)
        
        if self.current_dataset:
            self.r_code_lines.append(f"{self.current_dataset} <- {self.current_dataset} %>%")
            self.r_code_lines.append(f"  mutate({variable} = {r_expression})")
        else:
            self.r_code_lines.append(f"{variable} <- {r_expression}")
    
    def _generate_if_statement(self, node: Dict[str, Any]):
        """Generate IF-THEN-ELSE using case_when"""
        condition = node.get('condition')
        then_clause = node.get('then_clause')
        else_clause = node.get('else_clause')
        
        # Convert SAS condition to R
        r_condition = self._convert_expression(condition)
        
        # Extract variable being assigned
        if '=' in then_clause:
            var_name = then_clause.split('=')[0].strip()
            then_value = then_clause.split('=')[1].strip().replace("'", '"')
            
            self.r_code_lines.append(f"{self.current_dataset} <- {self.current_dataset} %>%")
            self.r_code_lines.append(f"  mutate({var_name} = case_when(")
            self.r_code_lines.append(f"    {r_condition} ~ {then_value},")
            
            if else_clause:
                else_value = else_clause.split('=')[1].strip().replace("'", '"')
                self.r_code_lines.append(f"    TRUE ~ {else_value}")
            else:
                self.r_code_lines.append(f"    TRUE ~ NA_character_")
            
            self.r_code_lines.append("  ))")
    
    def _generate_proc_means(self, node: Dict[str, Any]):
        """Generate PROC MEANS as dplyr summarise"""
        options = node.get('options', {})
        dataset = options.get('data', self.current_dataset)
        
        self.r_code_lines.append(f"# PROC MEANS: Summary statistics")
        
        if self.variables:
            self.r_code_lines.append(f"summary_stats <- {dataset} %>%")
            self.r_code_lines.append("  summarise(")
            
            for i, var in enumerate(self.variables):
                comma = "," if i < len(self.variables) - 1 else ""
                self.r_code_lines.append(f"    N_{var} = sum(!is.na({var})),")
                self.r_code_lines.append(f"    Mean_{var} = mean({var}, na.rm = TRUE),")
                self.r_code_lines.append(f"    Median_{var} = median({var}, na.rm = TRUE),")
                self.r_code_lines.append(f"    Min_{var} = min({var}, na.rm = TRUE),")
                self.r_code_lines.append(f"    Max_{var} = max({var}, na.rm = TRUE){comma}")
            
            self.r_code_lines.append("  )")
            self.r_code_lines.append("print(summary_stats)")
    
    def _generate_proc_freq(self, node: Dict[str, Any]):
        """Generate PROC FREQ as count + mutate"""
        options = node.get('options', {})
        dataset = options.get('data', self.current_dataset)
        
        self.r_code_lines.append(f"# PROC FREQ: Frequency distribution")
        
        if hasattr(self, 'table_variables') and self.table_variables:
            for var in self.table_variables:
                self.r_code_lines.append(f"freq_{var} <- {dataset} %>%")
                self.r_code_lines.append(f"  count({var}) %>%")
                self.r_code_lines.append("  mutate(")
                self.r_code_lines.append("    Percent = (n / sum(n)) * 100,")
                self.r_code_lines.append("    CumulativeFreq = cumsum(n),")
                self.r_code_lines.append("    CumulativePercent = cumsum(Percent)")
                self.r_code_lines.append("  )")
                self.r_code_lines.append(f"print(freq_{var})")
    
    def _generate_proc_sort(self, node: Dict[str, Any]):
        """Generate PROC SORT as arrange"""
        options = node.get('options', {})
        dataset = options.get('data', self.current_dataset)
        out_dataset = options.get('out', dataset + '_sorted')
        
        self.r_code_lines.append(f"# PROC SORT: Sorting data")
        
        if hasattr(self, 'by_variables') and self.by_variables:
            sort_vars = []
            for var in self.by_variables:
                if hasattr(self, 'by_descending') and self.by_descending:
                    sort_vars.append(f"desc({var})")
                else:
                    sort_vars.append(var)
            
            self.r_code_lines.append(f"{out_dataset} <- {dataset} %>%")
            self.r_code_lines.append(f"  arrange({', '.join(sort_vars)})")
    
    def _generate_proc_sql(self, node: Dict[str, Any]):
        """Generate PROC SQL"""
        self.r_code_lines.append("# PROC SQL: SQL query")
        self.r_code_lines.append("# Note: SQL statements will be converted to dplyr")
    
    def _convert_expression(self, expr: str) -> str:
        """Convert SAS expression to R expression"""
        if not expr:
            return ""
        
        # Convert operators
        r_expr = expr.replace('.', 'NA')
        r_expr = r_expr.replace(' and ', ' & ')
        r_expr = r_expr.replace(' or ', ' | ')
        r_expr = r_expr.replace(' not ', ' !')
        r_expr = r_expr.replace(' eq ', ' == ')
        r_expr = r_expr.replace(' ne ', ' != ')
        r_expr = r_expr.replace(' lt ', ' < ')
        r_expr = r_expr.replace(' le ', ' <= ')
        r_expr = r_expr.replace(' gt ', ' > ')
        r_expr = r_expr.replace(' ge ', ' >= ')
        
        return r_expr
    
    def add_inline_data_row(self, row: List[str]):
        """Add row of inline data"""
        self.inline_data.append(row)


# Example usage
if __name__ == "__main__":
    ast = [
        {'type': 'data_step', 'dataset': 'example', 'library': 'work'},
        {'type': 'input', 'variables': [
            {'name': 'ID', 'type': 'character'},
            {'name': 'Age', 'type': 'numeric'},
            {'name': 'Salary', 'type': 'numeric'}
        ]},
        {'type': 'datalines'},
        {'type': 'run'},
        {'type': 'proc_means', 'options': {'data': 'example'}},
        {'type': 'var', 'variables': ['Age', 'Salary']},
        {'type': 'run'}
    ]
    
    generator = RCodeGenerator()
    
    # Simulate inline data
    generator.inline_data = [
        ['A01', '25', '50000'],
        ['A02', '30', '60000']
    ]
    
    r_code = generator.generate(ast)
    print(r_code)
